language: php

php:
  - 7
  - 7.1
  - nightly

before_script:
  - composer install --prefer-dist -o

script:
  - ./vendor/bin/phpunit --coverage-clover ./clover.xml
  - if php -i |grep -qE xdebug; then ./vendor/bin/humbug; fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ -f clover.xml ]; then php ocular.phar code-coverage:upload --format=php-clover ./clover.xml; fi
