os: linux
dist: focal
language: php

php:
  - 7.4
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update

install:
  - |
    if [ $TRAVIS_PHP_VERSION = 'nightly' ]; then
      travis_retry composer install --ignore-platform-reqs;
    else
      travis_retry composer install;
    fi

script:
  - ./vendor/bin/phpunit

jobs:
  allow_failures:
    - php: nightly

  include:
    - stage: Test
      env: DEPENDENCIES=low
      install: travis_retry composer update --prefer-lowest

    - stage: Test
      env: DEPENDENCIES=dev
      if: type = cron
      install:
        - composer config minimum-stability dev
        - travis_retry composer update

    - stage: Quality
      env: TEST_COVERAGE=1
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - ./vendor/bin/phpunit --coverage-clover ./clover.xml
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml

    - stage: Quality
      env: CODE_STYLE=1
      script:
        - ./vendor/bin/phpcs

    - stage: Quality
      env: MUTATION=1
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for mutation"; exit 1; fi
      script:
        - ./vendor/bin/phpunit --coverage-xml=build/coverage-xml --log-junit=build/junit.xml
        - ./vendor/bin/infection -s --threads=$(nproc) --coverage=build

    - stage: Quality
      env: STATIC_ANALYSIS=1
      script:
        - ./vendor/bin/phpstan analyse
